# Generated by Django 3.0.7 on 2020-07-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fechaCita',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tipoCita',
        ),
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('C', 'Cancelada'), ('R', 'Reservada'), ('L', 'Libre'), ('F', 'Finalizada')], default='L', max_length=250)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Medico')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='disponible',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Disponible'),
        ),
    ]
