# Generated by Django 3.0.7 on 2020-07-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200727_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Paciente',
        ),
    ]
