# Generated by Django 3.0.7 on 2020-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200727_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
