# Generated by Django 3.0.8 on 2020-07-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200728_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
